#!/bin/bash

REPOROOT="$(git rev-parse --show-toplevel)"
OUT="out.build"

listen() {
    cd $REPOROOT
    EXIT=$1
    shift
    start=`date +%s`
    RESULT="$( $@ )"

    if [ $? -ne $EXIT ]; then
        STAT="\e[91mFAILED"
    else
        STAT="\e[92mok"
    fi
    end=`date +%s`
    runtime=$((end-start))
    echo "$STAT\e[0m\t\t$runtime\t\t$@" >> $OUT
}

echo "RESULT\t\tTIME\t\tCOMMAND" > out.build

listen 0 grep -oE "cargo.+$" ${REPOROOT}/.travis.yml | bash
listen 1 grep "\s$" -r -nr --include \*.rs
listen 0 cargo build --release
listen 0 cargo test
listen 0 cargo +nightly clippy
listen 0 cargo tarpaulin -v
listen 0 .${REPOROOT}/script/build_example

cat $OUT
rm $OUT
