#!/bin/bash
set -e

EXIT_CODE=0

if [ -z "$REPOROOT" ]; then
    echo "Sourcing Pathfinder Setup..."
    source $(git rev-parse --show-toplevel)/script/utils/setup
fi

for file in $REPOROOT/tests/*; do
    while read line; do
	[ -z "$line" ] && continue
	echo -e -n "tests/$(basename $file) - ${line} ... "
	eval "${line}" >/dev/null
	E=$?
	if [ "$E" != "0" ]; then
	   echo -e "\e[91mFAILED\e[0m"
	   EXIT_CODE=1;
	else
	   echo -e "\e[92mok\e[0m"
	fi
    done <$file
done

exit $EXIT_CODE

