#!/bin/bash
set -e

if [ -z "$REPOROOT" ]; then
    source $(git rev-parse --show-toplevel)/script/utils/setup
fi

EXECUTED=""

for file in $REPOROOT/tests/$1*; do
    while read -r line; do
	[ -z "$line" ] && continue
        line_nospaces="$(echo -e ${line} | tr -d '[:space:]')"
        for prev in $EXECUTED; do
            if [ "$line_nospaces" == "$prev" ]; then
                echo -e "\n\e[94mCommand '$prev' already executed, and will be skipped.\e[0m\n"
                unset line
                break
            fi
        done

	[ -z "$line" ] && continue
	echo -e "\n\e[94mFILE: tests/$(basename $file) - COMMAND: ${line} \e[0m\n"
	eval "cd $REPOROOT && ${line}"
        EXECUTED="$line_nospaces $EXECUTED"
    done <$file
done

echo -e "\e[92mSUCCESS\e[0m"

